-- ⚠️ AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
-- This migration is generated by a script in backend/scripts/migrations/.
-- To make changes, edit the generator script and re-run it.
-- The user will handle migration generation and application.
--
-- publicAt cascade: project.public_at → child products (tasks, attachments)
-- Row-local public read requires each child to carry its own public_at, mirroring its project.

-- 1. One-time backfill of existing rows.
UPDATE tasks c
SET public_at = p.public_at
FROM projects p
WHERE c.project_id = p.id
  AND c.public_at IS DISTINCT FROM p.public_at;
--> statement-breakpoint
UPDATE attachments c
SET public_at = p.public_at
FROM projects p
WHERE c.project_id = p.id
  AND c.public_at IS DISTINCT FROM p.public_at;
--> statement-breakpoint

-- 2. Cascade on project (un)publish. Fires only when public_at actually changes; rewrites only
--    children whose value differs (cheap, idempotent).
CREATE OR REPLACE FUNCTION cascade_public_at_from_project() RETURNS trigger AS $$
BEGIN
  IF NEW.public_at IS DISTINCT FROM OLD.public_at THEN
  UPDATE tasks
    SET public_at = NEW.public_at
    WHERE project_id = NEW.id AND public_at IS DISTINCT FROM NEW.public_at;
  UPDATE attachments
    SET public_at = NEW.public_at
    WHERE project_id = NEW.id AND public_at IS DISTINCT FROM NEW.public_at;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint
DROP TRIGGER IF EXISTS trg_cascade_public_at_from_project ON projects;
--> statement-breakpoint
CREATE TRIGGER trg_cascade_public_at_from_project
  AFTER UPDATE OF public_at ON projects
  FOR EACH ROW
  EXECUTE FUNCTION cascade_public_at_from_project();
--> statement-breakpoint

-- 3. Inherit the parent project's public_at on child insert, unless the caller set it explicitly.
CREATE OR REPLACE FUNCTION inherit_public_at_from_project() RETURNS trigger AS $$
BEGIN
  IF NEW.public_at IS NULL AND NEW.project_id IS NOT NULL THEN
    SELECT p.public_at INTO NEW.public_at FROM projects p WHERE p.id = NEW.project_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint
DROP TRIGGER IF EXISTS trg_inherit_public_at_tasks ON tasks;
--> statement-breakpoint
CREATE TRIGGER trg_inherit_public_at_tasks
  BEFORE INSERT ON tasks
  FOR EACH ROW
  EXECUTE FUNCTION inherit_public_at_from_project();
--> statement-breakpoint
DROP TRIGGER IF EXISTS trg_inherit_public_at_attachments ON attachments;
--> statement-breakpoint
CREATE TRIGGER trg_inherit_public_at_attachments
  BEFORE INSERT ON attachments
  FOR EACH ROW
  EXECUTE FUNCTION inherit_public_at_from_project();
